x = "https://x.com/nevar_eu"
github = "https://github.com/nevar-bot"
instagram = "https://instagram.com/nevar_eu"
support = "/support"
invite = "/invite"
vote = "https://top.gg/bot/860229767991263242/vote"